2019-03-26 18:40:49,966 - log.py[line:37] - INFO start runing test suite ...' 
2019-03-26 18:40:49,969 - log.py[line:37] - INFO AppSsoTest setUpClass' 
2019-03-26 18:40:49,976 - log.py[line:37] - INFO into test_login1' 
2019-03-26 18:40:50,401 - log.py[line:41] - ERROR testLogin1FAIL' 
2019-03-26 18:40:50,410 - log.py[line:37] - INFO into test_login2' 
2019-03-26 18:40:50,520 - log.py[line:37] - INFO testLogin2 PASS' 
2019-03-27 10:14:33,417 - log.py[line:37] - INFO start runing test suite ... 
2019-03-27 10:14:33,423 - log.py[line:37] - INFO AppSsoTest setUpClass 
2019-03-27 10:14:33,430 - log.py[line:37] - INFO into test_login1 
2019-03-27 10:14:34,158 - log.py[line:41] - ERROR testLogin1FAIL 
2019-03-27 10:14:34,171 - log.py[line:37] - INFO into test_login2 
2019-03-27 10:14:34,466 - log.py[line:37] - INFO testLogin2 PASS 
2019-03-27 10:20:11,507 - log.py[line:37] - INFO start runing test suite ... 
2019-03-27 10:20:11,510 - log.py[line:37] - INFO Into AppSsoTest setUpClass ... 
2019-03-27 10:20:11,517 - log.py[line:37] - INFO Into testLogin1 ... 
2019-03-27 10:20:12,176 - log.py[line:41] - ERROR testLogin1 FAIL 
2019-03-27 10:20:12,186 - log.py[line:37] - INFO Into testLogin2 ... 
2019-03-27 10:20:12,467 - log.py[line:37] - INFO testLogin2 PASS 
2019-03-27 10:25:16,637 - log.py[line:37] - INFO start runing test suite ... 
2019-03-27 10:25:16,640 - log.py[line:37] - INFO Into AppSsoTest setUpClass ... 
2019-03-27 10:25:16,648 - log.py[line:37] - INFO Into testLogin1 ... 
2019-03-27 10:25:17,144 - log.py[line:41] - ERROR testLogin1 FAIL 
2019-03-27 10:25:17,157 - log.py[line:37] - INFO Into testLogin2 ... 
2019-03-27 10:25:17,315 - log.py[line:37] - INFO testLogin2 PASS 
2019-03-27 10:51:24,474 - log.py[line:37] - INFO start runing test suite ... 
2019-03-27 10:51:24,477 - log.py[line:37] - INFO Into AppSsoTest setUpClass ... 
2019-03-27 10:51:24,486 - log.py[line:37] - INFO Into testLogin1 ... 
2019-03-27 10:51:25,286 - log.py[line:41] - ERROR testLogin1 FAIL 
2019-03-27 10:51:25,301 - log.py[line:37] - INFO Into testLogin2 ... 
2019-03-27 10:51:25,572 - log.py[line:37] - INFO testLogin2 PASS 
2019-03-27 10:52:53,384 - log.py[line:37] - INFO start runing test suite ... 
2019-03-27 10:52:53,390 - log.py[line:37] - INFO Into AppSsoTest setUpClass ... 
2019-03-27 10:52:53,398 - log.py[line:37] - INFO Into testLogin1 ... 
2019-03-27 10:52:53,836 - log.py[line:41] - ERROR testLogin1 FAIL 
2019-03-27 10:52:53,839 - log.py[line:37] - INFO Into testLogin2 ... 
2019-03-27 10:52:53,917 - log.py[line:37] - INFO testLogin2 PASS 
2019-03-27 10:54:17,483 - log.py[line:37] - INFO start runing test suite ... 
2019-03-27 10:54:17,486 - log.py[line:37] - INFO Into AppSsoTest setUpClass ... 
2019-03-27 10:54:17,494 - log.py[line:37] - INFO Into testLogin1 ... 
2019-03-27 10:54:17,937 - log.py[line:41] - ERROR testLogin1 FAIL 
2019-03-27 10:54:17,940 - log.py[line:37] - INFO Into testLogin2 ... 
2019-03-27 10:54:18,061 - log.py[line:37] - INFO testLogin2 PASS 
2019-03-27 10:55:32,836 - log.py[line:37] - INFO start runing test suite ... 
2019-03-27 10:55:32,841 - log.py[line:37] - INFO Into AppSsoTest setUpClass ... 
2019-03-27 10:55:32,848 - log.py[line:37] - INFO Into testLogin1 ... 
2019-03-27 10:55:33,394 - log.py[line:41] - ERROR testLogin1 FAIL 
2019-03-27 10:55:33,411 - log.py[line:37] - INFO Into testLogin2 ... 
2019-03-27 10:55:33,599 - log.py[line:37] - INFO testLogin2 PASS 
2019-03-27 11:00:38,740 - log.py[line:37] - INFO start runing test suite ... 
2019-03-27 11:00:38,743 - log.py[line:37] - INFO Into AppSsoTest setUpClass ... 
2019-03-27 11:00:38,752 - log.py[line:37] - INFO Into testLogin1 ... 
2019-03-27 11:00:39,266 - log.py[line:41] - ERROR testLogin1 FAIL 
2019-03-27 11:00:39,276 - log.py[line:37] - INFO Into testLogin2 ... 
2019-03-27 11:00:39,388 - log.py[line:37] - INFO testLogin2 PASS 
2019-03-27 11:04:03,210 - log.py[line:37] - INFO start runing test suite ... 
2019-03-27 11:04:03,214 - log.py[line:37] - INFO Into AppSsoTest setUpClass ... 
2019-03-27 11:04:03,221 - log.py[line:37] - INFO Into testLogin1 ... 
2019-03-27 11:04:03,812 - log.py[line:41] - ERROR testLogin1 FAIL 
2019-03-27 11:04:03,835 - log.py[line:37] - INFO Into testLogin2 ... 
2019-03-27 11:04:04,036 - log.py[line:37] - INFO testLogin2 PASS 
2019-03-27 11:08:49,096 - log.py[line:37] - INFO start runing test suite ... 
2019-03-27 11:08:49,101 - log.py[line:37] - INFO Into AppSsoTest setUpClass ... 
2019-03-27 11:08:49,108 - log.py[line:37] - INFO Into testLogin1 ... 
2019-03-27 11:08:49,881 - log.py[line:41] - ERROR testLogin1 FAIL 
2019-03-27 11:08:49,904 - log.py[line:37] - INFO Into testLogin2 ... 
2019-03-27 11:08:50,009 - log.py[line:37] - INFO testLogin2 PASS 
2019-03-27 11:08:58,292 - log.py[line:37] - INFO start runing test suite ... 
2019-03-27 11:08:58,295 - log.py[line:37] - INFO Into AppSsoTest setUpClass ... 
2019-03-27 11:08:58,302 - log.py[line:37] - INFO Into testLogin1 ... 
2019-03-27 11:08:58,723 - log.py[line:37] - INFO testLogin1 PASS 
2019-03-27 11:08:58,737 - log.py[line:37] - INFO Into testLogin2 ... 
2019-03-27 11:08:58,844 - log.py[line:37] - INFO testLogin2 PASS 
